// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PokeDAL.Models;

public partial class Pokemon
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int? BaseExperience { get; set; }

    public int? Height { get; set; }

    public bool? IsDefault { get; set; }

    public int? Order { get; set; }

    public int? Weight { get; set; }
}